# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: items.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bitems.proto\x12\x05items\"\x1c\n\x0eGetItemRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x11\x43reateItemRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\"7\n\x0cItemResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x32\x81\x01\n\x0bItemService\x12\x35\n\x07GetItem\x12\x15.items.GetItemRequest\x1a\x13.items.ItemResponse\x12;\n\nCreateItem\x12\x18.items.CreateItemRequest\x1a\x13.items.ItemResponseB\x14Z\x12go-service/grpc/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'items_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022go-service/grpc/pb'
  _globals['_GETITEMREQUEST']._serialized_start=22
  _globals['_GETITEMREQUEST']._serialized_end=50
  _globals['_CREATEITEMREQUEST']._serialized_start=52
  _globals['_CREATEITEMREQUEST']._serialized_end=100
  _globals['_ITEMRESPONSE']._serialized_start=102
  _globals['_ITEMRESPONSE']._serialized_end=157
  _globals['_ITEMSERVICE']._serialized_start=160
  _globals['_ITEMSERVICE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
